# Connecting to our MySQL database
Since we have a MySQL database, we can connect to it using mysql and pymysql.

In [1]:
%load_ext sql

## Exercise: Basic Filtering with Comparison Operators

### Task 1: Filtering Data from the `Access_to_Basic_Services` Table

You will be working with the **`united_nations.access_to_basic_services`** table.

The goal is to select and filter records based on specific criteria.

---

### Columns to SELECT
- `Country_name`
- `Time_period`
- `Pct_managed_drinking_water_services`
- `Pct_managed_sanitation_services`
- `Est_population_in_millions`
- `Est_gdp_in_billions`

---

###  Filtering Criteria
Use the **`WHERE`** clause to filter for:

- Countries:
  - Nigeria  
  - Ethiopia  
  - Congo  
  - Egypt  
  - Tanzania  
  - Kenya  
  - South Africa  

- **Time period:** Between **2019 and 2020**

Use the **`OR`** operator to include multiple countries in your filter.

In [4]:
%%sql
-- Task 1: Basic Filtering with Comparison Operators
-- Selecting key columns from the Access_to_Basic_Services table
-- Filtering for specific African countries and time periods (2019â€“2020)

SELECT 
    Country_name,
    Time_period,
    Pct_managed_drinking_water_services,
    Pct_managed_sanitation_services,
    Est_population_in_millions,
    Est_gdp_in_billions
FROM access_to_basic_services
WHERE 
    (Country_name = 'Nigeria'
     OR Country_name = 'Ethiopia'
     OR Country_name = 'Congo'
     OR Country_name = 'Egypt'
     OR Country_name = 'Tanzania'
     OR Country_name = 'Kenya'
     OR Country_name = 'South Africa')
    AND (Time_period BETWEEN 2019 AND 2020);

 * mysql+pymysql://root:***@localhost:3306/united_nations
12 rows affected.

[('Egypt', 2019, Decimal('99.33'), Decimal('97.00'), None, None),
 ('Egypt', 2020, Decimal('99.33'), Decimal('97.67'), None, None),
 ('Ethiopia', 2019, Decimal('57.00'), Decimal('11.67'), Decimal('114.120594'), Decimal('95.91')),
 ('Ethiopia', 2020, Decimal('58.00'), Decimal('11.67'), Decimal('117.190911'), Decimal('107.66')),
 ('Kenya', 2019, Decimal('66.33'), Decimal('33.33'), Decimal('50.951450'), Decimal('100.38')),
 ('Kenya', 2020, Decimal('67.00'), Decimal('33.67'), Decimal('51.985780'), Decimal('100.67')),
 ('Congo', 2019, Decimal('69.00'), Decimal('17.67'), None, None),
 ('Congo', 2020, Decimal('69.00'), Decimal('17.67'), None, None),
 ('South Africa', 2019, Decimal('91.67'), Decimal('78.00'), Decimal('58.087055'), Decimal('388.53')),
 ('South Africa', 2020, Decimal('92.00'), Decimal('78.67'), Decimal('58.801927'), Decimal('337.62')),
 ('Nigeria', 2019, Decimal('75.67'), Decimal('41.67'), Decimal('203.304492'), Decimal('448.12')),
 ('Nigeria', 2020, Decimal('77.33'), Decimal('42.67'), Decimal('208.327405'), Decimal('432.20'))]

# Task 2: Streamlining with the IN Operator
Building on the first task, you might have noticed that using multiple OR operators can make the query lengthy and a bit complicated. The 'IN' operator offers a more efficient way to achieve the same result. The IN operator allows you to specify multiple values in a WHERE clause, making the query more concise. Try to retrieve data for the same list of countries for the same time range, but this time, use the IN operator to simplify your query.

In [5]:
%%sql
-- Task 2: Streamlining with the IN Operator
-- Using the IN operator to simplify filtering for multiple countries
-- Fetching the same columns and time range (2019â€“2020) as in Task 1

SELECT 
    Country_name,
    Time_period,
    Pct_managed_drinking_water_services,
    Pct_managed_sanitation_services,
    Est_population_in_millions,
    Est_gdp_in_billions
FROM access_to_basic_services
WHERE 
    Country_name IN ('Nigeria', 'Ethiopia', 'Congo', 'Egypt', 'Tanzania', 'Kenya', 'South Africa')
    AND Time_period BETWEEN 2019 AND 2020;

 * mysql+pymysql://root:***@localhost:3306/united_nations
12 rows affected.

[('Egypt', 2019, Decimal('99.33'), Decimal('97.00'), None, None),
 ('Egypt', 2020, Decimal('99.33'), Decimal('97.67'), None, None),
 ('Ethiopia', 2019, Decimal('57.00'), Decimal('11.67'), Decimal('114.120594'), Decimal('95.91')),
 ('Ethiopia', 2020, Decimal('58.00'), Decimal('11.67'), Decimal('117.190911'), Decimal('107.66')),
 ('Kenya', 2019, Decimal('66.33'), Decimal('33.33'), Decimal('50.951450'), Decimal('100.38')),
 ('Kenya', 2020, Decimal('67.00'), Decimal('33.67'), Decimal('51.985780'), Decimal('100.67')),
 ('Congo', 2019, Decimal('69.00'), Decimal('17.67'), None, None),
 ('Congo', 2020, Decimal('69.00'), Decimal('17.67'), None, None),
 ('South Africa', 2019, Decimal('91.67'), Decimal('78.00'), Decimal('58.087055'), Decimal('388.53')),
 ('South Africa', 2020, Decimal('92.00'), Decimal('78.67'), Decimal('58.801927'), Decimal('337.62')),
 ('Nigeria', 2019, Decimal('75.67'), Decimal('41.67'), Decimal('203.304492'), Decimal('448.12')),
 ('Nigeria', 2020, Decimal('77.33'), Decimal('42.67'), Decimal('208.327405'), Decimal('432.20'))]

## Task 3: Combining Multiple Conditions

In this task, weâ€™ll explore how to use the **`<=` (less than or equal to)** operator to filter records based on a threshold value.  

Weâ€™ll continue working with the **`united_nations.access_to_basic_services`** table.

###  Objective
To identify countries that have **50% or less of their population** with access to managed sanitation services in the year **2020**.  

This analysis helps highlight countries with critical sanitation challenges.

---

###  Columns to SELECT
- `Region`
- `Country_name`
- `Time_period`
- `Pct_managed_drinking_water_services`
- `Pct_managed_sanitation_services`
- `Est_population_in_millions`
- `Est_gdp_in_billions`

---

###  Filtering Criteria
- **Time_period:** 2020  
- **Pct_managed_sanitation_services:** â‰¤ 50%

Weâ€™ll use the **`<=` operator** to set our condition and retrieve only those records that meet the threshold.

In [6]:
%%sql
-- Task 3: Combining Multiple Conditions
-- Selecting countries with 50% or less access to managed sanitation services in 2020

SELECT
    Region,
    Country_name,
    Time_period,
    Pct_managed_drinking_water_services,
    Pct_managed_sanitation_services,
    Est_population_in_millions,
    Est_gdp_in_billions
FROM access_to_basic_services
WHERE 
    Time_period = 2020
    AND Pct_managed_sanitation_services <= 50
ORDER BY Pct_managed_sanitation_services ASC;

 * mysql+pymysql://root:***@localhost:3306/united_nations
41 rows affected.

[('Sub-Saharan Africa', 'Ethiopia', 2020, Decimal('58.00'), Decimal('11.67'), Decimal('117.190911'), Decimal('107.66')),
 ('Sub-Saharan Africa', 'Madagascar', 2020, Decimal('56.33'), Decimal('13.00'), Decimal('28.225177'), Decimal('13.05')),
 ('Sub-Saharan Africa', 'Central African Republic', 2020, Decimal('38.33'), Decimal('15.00'), Decimal('5.343020'), Decimal('2.33')),
 ('Sub-Saharan Africa', 'Democratic Republic of the Congo', 2020, Decimal('47.67'), Decimal('15.33'), None, None),
 ('Sub-Saharan Africa', 'Sierra Leone', 2020, Decimal('65.00'), Decimal('17.33'), Decimal('8.233970'), Decimal('4.06')),
 ('Sub-Saharan Africa', 'Benin', 2020, Decimal('65.33'), Decimal('17.33'), Decimal('12.643123'), Decimal('15.65')),
 ('Sub-Saharan Africa', 'Congo', 2020, Decimal('69.00'), Decimal('17.67'), None, None),
 ('Sub-Saharan Africa', 'Liberia', 2020, Decimal('75.00'), Decimal('17.67'), Decimal('5.087584'), Decimal('3.04')),
 ('Sub-Saharan Africa', 'Chad', 2020, Decimal('52.67'), Decimal('18.67'), Decimal('16.644701'), Decimal('10.72')),
 ('Sub-Saharan Africa', 'Guinea-Bissau', 2020, Decimal('60.00'), Decimal('19.33'), Decimal('2.015828'), Decimal('1.43')),
 ('Sub-Saharan Africa', 'Togo', 2020, Decimal('70.67'), Decimal('20.00'), Decimal('8.442580'), Decimal('7.57')),
 ('Sub-Saharan Africa', 'Uganda', 2020, Decimal('61.00'), Decimal('21.67'), Decimal('44.404611'), Decimal('37.60')),
 ('Sub-Saharan Africa', 'South Sudan', 2020, Decimal('48.33'), Decimal('22.33'), Decimal('10.606227'), None),
 ('Sub-Saharan Africa', 'Ghana', 2020, Decimal('84.67'), Decimal('23.00'), Decimal('32.180401'), Decimal('70.04')),
 ('Sub-Saharan Africa', 'Niger', 2020, Decimal('57.33'), Decimal('24.67'), Decimal('24.333639'), Decimal('13.74')),
 ('Sub-Saharan Africa', 'Burkina Faso', 2020, Decimal('53.33'), Decimal('25.00'), Decimal('21.522626'), Decimal('17.93')),
 ('Oceania', 'Papua New Guinea', 2020, Decimal('56.67'), Decimal('27.67'), Decimal('9.749640'), Decimal('23.85')),
 ('Sub-Saharan Africa', 'Malawi', 2020, Decimal('74.33'), Decimal('28.67'), Decimal('19.377061'), Decimal('12.18')),
 ('Sub-Saharan Africa', 'Guinea', 2020, Decimal('67.33'), Decimal('32.33'), Decimal('13.205153'), Decimal('14.18')),
 ('Sub-Saharan Africa', 'Zambia', 2020, Decimal('66.67'), Decimal('32.67'), Decimal('18.927715'), Decimal('18.11')),
 ('Sub-Saharan Africa', 'Kenya', 2020, Decimal('67.00'), Decimal('33.67'), Decimal('51.985780'), Decimal('100.67')),
 ('Sub-Saharan Africa', 'United Republic of Tanzania', 2020, Decimal('65.00'), Decimal('34.00'), None, None),
 ('Sub-Saharan Africa', "CÃ´te d'Ivoire", 2020, Decimal('70.67'), Decimal('34.67'), None, None),
 ('Sub-Saharan Africa', 'Namibia', 2020, Decimal('83.67'), Decimal('35.00'), Decimal('2.489098'), Decimal('10.58')),
 ('Latin America and the Caribbean', 'Haiti', 2020, Decimal('65.00'), Decimal('36.00'), Decimal('11.306801'), Decimal('14.51')),
 ('Sub-Saharan Africa', 'Zimbabwe', 2020, Decimal('68.00'), Decimal('36.33'), Decimal('15.669666'), Decimal('21.51')),
 ('Sub-Saharan Africa', 'Somalia', 2020, Decimal('57.33'), Decimal('40.00'), Decimal('16.537016'), Decimal('6.88')),
 ('Northern Africa and Western Asia', 'Sudan', 2020, Decimal('62.33'), Decimal('40.33'), Decimal('44.440486'), Decimal('27.03')),
 ('Sub-Saharan Africa', 'Mozambique', 2020, Decimal('66.67'), Decimal('40.33'), Decimal('31.178239'), Decimal('14.03')),
 ('Sub-Saharan Africa', 'Nigeria', 2020, Decimal('77.33'), Decimal('42.67'), Decimal('208.327405'), Decimal('432.20')),
 ('Sub-Saharan Africa', 'Cameroon', 2020, Decimal('64.00'), Decimal('43.00'), Decimal('26.491087'), Decimal('40.77')),
 ('Sub-Saharan Africa', 'Burundi', 2020, Decimal('70.33'), Decimal('44.33'), Decimal('12.220227'), Decimal('2.65')),
 ('Sub-Saharan Africa', 'Gambia', 2020, Decimal('79.33'), Decimal('44.33'), None, None),
 ('Oceania', 'Solomon Islands', 2020, Decimal('72.33'), Decimal('44.67'), Decimal('0.691191'), Decimal('1.54')),
 ('Oceania', 'Kiribati', 2020, Decimal('77.00'), Decimal('45.33'), Decimal('0.126463'), Decimal('0.18')),
 ('Sub-Saharan Africa', 'Sao Tome and Principe', 2020, Decimal('77.33'), Decimal('46.00'), Decimal('0.218641'), Decimal('0.47')),
 ('Sub-Saharan Africa', 'Mali', 2020, Decimal('83.67'), Decimal('46.00'), Decimal('21.224040'), Decimal('17.47')),
 ('Sub-Saharan Africa', 'Angola', 2020, Decimal('52.33'), Decimal('47.00'), Decimal('33.428486'), Decimal('53.62')),
 ('Sub-Saharan Africa', 'Gabon', 2020, Decimal('73.33'), Decimal('47.00'), Decimal('2.292573'), Decimal('15.31')),
 ('Sub-Saharan Africa', 'Mauritania', 2020, Decimal('70.33'), Decimal('48.00'), Decimal('4.498604'), Decimal('8.41')),
 ('Sub-Saharan Africa', 'Lesotho', 2020, Decimal('76.33'), Decimal('49.67'), Decimal('2.254100'), Decimal('2.23'))]